version: '2.4'
services:
  db:
    container_name: 'graphql-dev'
    image: 'postgres:9-alpine'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=graphql
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=graphql-dev

  adminer:
    image: adminer
    ports:
      - 5480:8080
